module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		project: './tsconfig.json',
	},
	plugins: ['import', '@typescript-eslint'],
	extends: ['plugin:import/typescript', 'prettier/@typescript-eslint'],
	rules: {
		'no-undef': 0,
		'@typescript-eslint/adjacent-overload-signatures': 2,
		'@typescript-eslint/array-type': 2,
		'@typescript-eslint/await-thenable': 2,
		'@typescript-eslint/ban-ts-ignore': 2,
		'@typescript-eslint/camelcase': 2,
		'@typescript-eslint/class-name-casing': 2,
		'@typescript-eslint/consistent-type-definitions': [2, 'interface'],
		'@typescript-eslint/generic-type-naming': 2,
		'@typescript-eslint/no-angle-bracket-type-assertion': 2,
		'@typescript-eslint/no-array-constructor': 2,
		'no-empty-function': 2,
		'@typescript-eslint/no-empty-function': 2,
		'@typescript-eslint/no-empty-interface': 2,
		'@typescript-eslint/no-extraneous-class': 2,
		'@typescript-eslint/no-floating-promises': 2,
		'@typescript-eslint/no-for-in-array': 2,
		'@typescript-eslint/no-inferrable-types': 2,
		'@typescript-eslint/no-misused-new': 2,
		'@typescript-eslint/no-namespace': 2,
		'@typescript-eslint/no-non-null-assertion': 2,
		'@typescript-eslint/no-object-literal-type-assertion': 2,
		'@typescript-eslint/no-require-imports': 2,
		'@typescript-eslint/no-this-alias': 2,
		'@typescript-eslint/no-unnecessary-qualifier': 2,
		'@typescript-eslint/no-unnecessary-type-assertion': 2,
		'@typescript-eslint/no-unused-vars': 2,
		'@typescript-eslint/no-use-before-define': 2,
		'@typescript-eslint/no-useless-constructor': 2,
		'@typescript-eslint/no-var-requires': 2,
		'@typescript-eslint/prefer-for-of': 2,
		'@typescript-eslint/prefer-function-type': 2,
		'@typescript-eslint/prefer-namespace-keyword': 2,
		'@typescript-eslint/prefer-includes': 2,
		'@typescript-eslint/prefer-readonly': 2,
		'@typescript-eslint/prefer-regexp-exec': 2,
		'@typescript-eslint/prefer-string-starts-ends-with': 2,
		'@typescript-eslint/require-array-sort-compare': 2,
		'@typescript-eslint/restrict-plus-operands': 2,
		'@typescript-eslint/strict-boolean-expressions': 2,
		'@typescript-eslint/triple-slash-reference': [
			2,
			{path: 'never', types: 'never', lib: 'never'},
		],
		'@typescript-eslint/unbound-method': 2,
		'@typescript-eslint/unified-signatures': 2,
	},
};
