module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		sourceType: 'module',
	},
	plugins: ['import', 'prefer-arrow', 'unicorn', '@typescript-eslint'],
	rules: {
		// Possible Errors
		'getter-return': 2,
		'no-async-promise-executor': 2,
		'no-compare-neg-zero': 2,
		'no-cond-assign': 2,
		'no-console': 2,
		'no-constant-condition': 2,
		'no-control-regex': 2,
		'no-debugger': 2,
		'no-dupe-args': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-empty': 2,
		'no-empty-character-class': 2,
		'no-ex-assign': 2,
		'no-extra-boolean-cast': 2,
		'no-func-assign': 2,
		'no-inner-declarations': 2,
		'no-invalid-regexp': 2,
		'no-misleading-character-class': 2,
		'no-obj-calls': 2,
		'no-prototype-builtins': 2,
		'no-regex-spaces': 2,
		'no-sparse-arrays': 2,
		'no-template-curly-in-string': 2,
		'no-unexpected-multiline': 2,
		'no-unreachable': 2,
		'no-unsafe-finally': 2,
		'no-unsafe-negation': 2,
		'require-atomic-updates': 2,
		'use-isnan': 2,
		'valid-typeof': 2,

		// Best Practices
		'array-callback-return': 2,
		'block-scoped-var': 2,
		'class-methods-use-this': 2,
		complexity: 2,
		'consistent-return': 2,
		'default-case': 2,
		eqeqeq: 2,
		'guard-for-in': 2,
		'no-caller': 2,
		'no-case-declarations': 2,
		'no-div-regex': 2,
		'no-else-return': 2,
		'no-empty-pattern': 2,
		'no-eq-null': 2,
		'no-eval': 2,
		'no-extend-native': 2,
		'no-extra-bind': 2,
		'no-extra-label': 2,
		'no-fallthrough': 2,
		'no-floating-decimal': 2,
		'no-global-assign': 2,
		'no-implicit-coercion': 2,
		'no-implicit-globals': 2,
		'no-implied-eval': 2,
		'no-invalid-this': 2,
		'no-iterator': 2,
		'no-labels': 2,
		'no-lone-blocks': 2,
		'no-loop-func': 2,
		'no-multi-str': 2,
		'no-new': 2,
		'no-new-func': 2,
		'no-new-wrappers': 2,
		'no-octal': 2,
		'no-octal-escape': 2,
		'no-param-reassign': 2,
		'no-proto': 2,
		'no-redeclare': 2,
		'no-return-assign': 2,
		'no-return-await': 2,
		'no-script-url': 2,
		'no-self-assign': 2,
		'no-self-compare': 2,
		'no-sequences': 2,
		'no-throw-literal': 2,
		'no-unmodified-loop-condition': 2,
		'no-unused-expressions': 2,
		'no-unused-labels': 2,
		'no-useless-call': 2,
		'no-useless-catch': 2,
		'no-useless-concat': 2,
		'no-useless-escape': 2,
		'no-useless-return': 2,
		'no-void': 2,
		'no-with': 2,
		'prefer-promise-reject-errors': 2,
		radix: 2,
		'require-await': 2,
		'require-unicode-regexp': 2,
		'vars-on-top': 2,
		'wrap-iife': 2,
		yoda: 2,

		// Variables
		'no-delete-var': 2,
		'no-label-var': 2,
		'no-shadow': 2,

		// Node.js and CommonJS
		'callback-return': 2,
		'handle-callback-err': 2,
		'no-buffer-constructor': 2,
		'no-mixed-requires': 2,
		'no-new-require': 2,
		'no-path-concat': 2,
		'no-sync': 2,

		// Stylistic Issues
		'func-name-matching': 2,
		'max-params': 2,
		'no-array-constructor': 2,
		'no-bitwise': 2,
		'no-lonely-if': 2,
		'no-multi-assign': 2,
		'no-negated-condition': 2,
		'no-nested-ternary': 2,
		'no-new-object': 2,
		'no-plusplus': 2,
		'no-unneeded-ternary': 2,
		'prefer-object-spread': 2,

		// ECMAScript 6
		'constructor-super': 2,
		'no-class-assign': 2,
		'no-const-assign': 2,
		'no-duplicate-imports': 2,
		'no-new-symbol': 2,
		'no-dupe-class-members': 2,
		'no-this-before-super': 2,
		'no-useless-rename': 2,
		'no-var': 2,
		'object-shorthand': 2,
		'prefer-arrow-callback': 2,
		'prefer-const': 2,
		'prefer-destructuring': 2,
		'prefer-rest-params': 2,
		'prefer-spread': 2,
		'prefer-template': 2,
		'require-yield': 2,

		// eslint-plugin-import
		'import/no-absolute-path': 2,
		'import/no-self-import': 2,
		'import/no-cycle': 2,
		'import/no-useless-path-segments': 2,
		'import/export': 2,
		'import/no-deprecated': 2,
		'import/no-extraneous-dependencies': 2,
		'import/first': 2,
		'import/no-duplicates': 2,
		'import/extensions': 2,
		'import/order': 2,
		'import/newline-after-import': 2,

		// eslint-plugin-prefer-arrow
		'prefer-arrow/prefer-arrow-functions': 2,

		// eslint-plugin-unicorn
		'unicorn/catch-error-name': 2,
		'unicorn/explicit-length-check': 2,
		'unicorn/filename-case': [2, {case: 'kebabCase'}],
		'unicorn/throw-new-error': 2,
		'unicorn/number-literal-case': 2,
		'unicorn/escape-case': 2,
		'unicorn/no-array-instanceof': 2,
		'unicorn/prefer-starts-ends-with': 2,
		'unicorn/import-index': 2,
		'unicorn/new-for-builtins': 2,
		'unicorn/regex-shorthand': 2,
		'unicorn/prefer-spread': 2,
		'unicorn/error-message': 2,
		'unicorn/no-unsafe-regex': 2,
		'unicorn/prefer-add-event-listener': 2,
		'unicorn/prefer-exponentiation-operator': 2,
		'unicorn/no-console-spaces': 2,
		'unicorn/no-unreadable-array-destructuring': 2,
		'unicorn/no-unused-properties': 2,
		'unicorn/prefer-node-append': 2,
		'unicorn/prefer-query-selector': 2,
		// Not published yet
		// 'unicorn/prefer-node-remove': 2,
		// 'unicorn/prefer-text-content': 2,

		// typescript-eslint
		'@typescript-eslint/adjacent-overload-signatures': 2,
		'@typescript-eslint/array-type': 2,
		'@typescript-eslint/camelcase': 2,
		'@typescript-eslint/class-name-casing': 2,
		'@typescript-eslint/explicit-function-return-type': [
			2,
			{allowExpressions: true},
		],
		'@typescript-eslint/no-angle-bracket-type-assertion': 2,
		'@typescript-eslint/no-array-constructor': 2,
		'@typescript-eslint/no-extraneous-class': 2,
		'@typescript-eslint/no-for-in-array': 2,
		'@typescript-eslint/no-inferrable-types': 2,
		'@typescript-eslint/no-misused-new': 2,
		'@typescript-eslint/no-object-literal-type-assertion': 2,
		'@typescript-eslint/no-this-alias': 2,
		'@typescript-eslint/no-unnecessary-type-assertion': 2,
		'@typescript-eslint/no-use-before-define': 2,
		'@typescript-eslint/no-useless-constructor': 2,
		'@typescript-eslint/no-var-requires': 2,
		// Not published yet
		// '@typescript-eslint/prefer-function-type': 2,
		'@typescript-eslint/prefer-namespace-keyword': 2,
		'@typescript-eslint/promise-function-async': 2,
		'@typescript-eslint/restrict-plus-operands': 2,
	},
	settings: {
		'import/extensions': ['.js', '.jsx', '.ts', '.tsx'],
		'import/parsers': {
			'@typescript-eslint/parser': ['.ts', '.tsx'],
		},
		'import/resolver': {
			node: {
				extensions: ['.js', '.jsx', '.ts', '.tsx'],
			},
		},
	},
};
