module.exports = {
	plugins: ['import'],
	rules: {
		'import/no-absolute-path': 2,
		'import/no-self-import': 2,
		'import/no-cycle': 2,
		'import/no-useless-path-segments': 2,
		'import/export': 2,
		'import/no-deprecated': 2,
		'import/first': 2,
		'import/no-duplicates': 2,
		'import/extensions': 2,
		'import/newline-after-import': 2,
		'import/no-anonymous-default-export': 2,
		'import/default': 2,
		'import/dynamic-import-chunkname': 0,
		'import/exports-last': 0,
		'import/group-exports': 2,
		'import/max-dependencies': 0,
		'import/named': 2,
		'import/namespace': 2,
		'import/no-amd': 2,
		'import/no-commonjs': 0, // TODO: enabled this on Node v14
		'import/no-default-export': 0,
		'import/no-dynamic-require': 0,
		'import/no-extraneous-dependencies': 0,
		'import/no-internal-modules': 0,
		'import/no-mutable-exports': 2,
		'import/no-named-as-default': 2,
		'import/no-named-as-default-member': 2,
		'import/no-named-default': 0,
		'import/no-named-export': 0,
		'import/no-namespace': 0,
		'import/no-nodejs-modules': 0,
		'import/no-relative-parent-imports': 0,
		'import/no-restricted-paths': 0,
		'import/no-unassigned-import': 0,
		'import/no-unresolved': 2,
		'import/no-unused-modules': [2, {unusedExports: true}],
		'import/no-webpack-loader-syntax': 2,
		'import/prefer-default-export': 0,
		'import/unambiguous': 0,

		'sort-imports': 0,
		'import/order': [2, {'newlines-between': 'always'}],
	},
};
