module.exports = {
	parser: '@typescript-eslint/parser',
	plugins: ['@typescript-eslint'],
	rules: {
		'@typescript-eslint/adjacent-overload-signatures': 2,
		'@typescript-eslint/array-type': 2,
		'@typescript-eslint/await-thenable': 2,
		'@typescript-eslint/ban-ts-ignore': 2,
		camelcase: 0,
		'@typescript-eslint/camelcase': 2,
		'@typescript-eslint/class-name-casing': 2,
		'@typescript-eslint/consistent-type-assertions': 2,
		'@typescript-eslint/consistent-type-definitions': [2, 'interface'],
		'@typescript-eslint/generic-type-naming': 2,
		'@typescript-eslint/no-array-constructor': 2,
		'no-empty-function': 0,
		'@typescript-eslint/no-empty-function': 2,
		'@typescript-eslint/no-empty-interface': 2,
		'@typescript-eslint/no-extraneous-class': 2,
		'@typescript-eslint/no-floating-promises': 2,
		'@typescript-eslint/no-for-in-array': 2,
		'@typescript-eslint/no-inferrable-types': 2,
		'@typescript-eslint/no-misused-new': 2,
		'@typescript-eslint/no-namespace': 2,
		'@typescript-eslint/no-non-null-assertion': 2,
		'@typescript-eslint/no-require-imports': 2,
		'@typescript-eslint/no-this-alias': 2,
		'@typescript-eslint/no-unnecessary-qualifier': 2,
		'@typescript-eslint/no-unnecessary-type-assertion': 2,
		'no-unused-vars': 0,
		'@typescript-eslint/no-unused-vars': 2,
		'@typescript-eslint/no-use-before-define': 2,
		'@typescript-eslint/no-useless-constructor': 2,
		'@typescript-eslint/no-var-requires': 2,
		'@typescript-eslint/prefer-for-of': 2,
		'@typescript-eslint/prefer-function-type': 2,
		'@typescript-eslint/prefer-namespace-keyword': 2,
		'@typescript-eslint/prefer-includes': 2,
		'@typescript-eslint/prefer-readonly': 2,
		'@typescript-eslint/prefer-regexp-exec': 2,
		'@typescript-eslint/prefer-string-starts-ends-with': 2,
		'@typescript-eslint/require-array-sort-compare': 2,
		'@typescript-eslint/restrict-plus-operands': 2,
		'@typescript-eslint/strict-boolean-expressions': 2,
		'@typescript-eslint/triple-slash-reference': [
			2,
			{path: 'never', types: 'never', lib: 'never'},
		],
		'@typescript-eslint/unbound-method': 2,
		'@typescript-eslint/unified-signatures': 2,
		'@typescript-eslint/interface-name-prefix': 2,
		'@typescript-eslint/no-explicit-any': 2,
		'@typescript-eslint/no-magic-numbers': 2,
		'@typescript-eslint/no-misused-promises': 2,
		'@typescript-eslint/no-unnecessary-condition': 2,
		'@typescript-eslint/no-unnecessary-type-arguments': 2,
		'require-await': 0,
		'@typescript-eslint/require-await': 2,

		'@typescript-eslint/promise-function-async': 0,
		'@typescript-eslint/ban-types': 0,
		'@typescript-eslint/explicit-function-return-type': 0,
		'@typescript-eslint/explicit-member-accessibility': 0,
		'@typescript-eslint/member-naming': 0,
		'@typescript-eslint/member-ordering': 0,
		'@typescript-eslint/no-parameter-properties': 0,
		'@typescript-eslint/no-type-alias': 0,
		'@typescript-eslint/typedef': 0,
	},
};
