module.exports = {
	plugins: ['unicorn'],
	rules: {
		'unicorn/catch-error-name': 2,
		'unicorn/custom-error-definition': 2,
		'unicorn/error-message': 2,
		'unicorn/escape-case': 2,
		'unicorn/explicit-length-check': 2,
		'unicorn/filename-case': [2, {case: 'kebabCase'}],
		'unicorn/import-index': 2,
		'unicorn/new-for-builtins': 2,
		'unicorn/no-array-instanceof': 2,
		'unicorn/no-console-spaces': 2,
		'unicorn/no-fn-reference-in-iterator': 2,
		'unicorn/no-for-loop': 2,
		'unicorn/no-new-buffer': 2,
		'unicorn/no-unreadable-array-destructuring': 2,
		'unicorn/no-unsafe-regex': 0,
		'unicorn/no-unused-properties': 2,
		'unicorn/no-zero-fractions': 2,
		'unicorn/number-literal-case': 2,
		'unicorn/prefer-add-event-listener': 2,
		'unicorn/prefer-event-key': 2,
		'unicorn/prefer-exponentiation-operator': 2,
		'unicorn/prefer-flat-map': 2,
		'unicorn/prefer-includes': 2,
		'unicorn/prefer-node-append': 2,
		'unicorn/prefer-node-remove': 2,
		'unicorn/prefer-query-selector': 2,
		'unicorn/prefer-spread': 2,
		'unicorn/prefer-starts-ends-with': 2,
		'unicorn/prefer-text-content': 2,
		'unicorn/prefer-type-error': 2,
		'unicorn/regex-shorthand': 2,
		'unicorn/throw-new-error': 2,
		'unicorn/consistent-function-scoping': 2,
		'unicorn/expiring-todo-comments': 0,
		'unicorn/no-abusive-eslint-disable': 2,
		'unicorn/no-hex-escape': 2,
		'unicorn/no-keyword-prefix': 0,
		'unicorn/no-process-exit': 0,
		'unicorn/prefer-dataset': 2,
		'unicorn/prefer-reflect-apply': 2,
		'unicorn/prefer-string-slice': 2,
		'unicorn/prevent-abbreviations': 0,
	},
};
